name: Build UpcomingSwitchGames

on:
  push:
    branches:
      - master
  pull_request:

jobs:
  version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.info.outputs.version }}
      standard_version: ${{ steps.info.outputs.standard_version }}
      DIST_NRO: ${{ steps.info.outputs.DIST_NRO }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Debug version
        run: |
          export VERSION=`git rev-parse --short HEAD`
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Release version
        if: github.event.inputs.release == 'true' && github.event.inputs.release != 'false' && !cancelled()
        run: |
          export VERSION="${{ github.event.inputs.version }}"
          echo "VERSION=${VERSION}" >> $GITHUB_ENV

      - name: Version
        id: info
        env:
          VERSION: ${{ env.VERSION }}
        run: |
          echo "version=${VERSION}" >> $GITHUB_OUTPUT
          echo "DIST_NRO=UpcomingSwitchGames-NintendoSwitch-${VERSION}" >> $GITHUB_OUTPUT
          echo $VERSION
          echo "${{  github.event.inputs.version }}"


  release:
    needs: [ build-switch, version ]
    runs-on: ubuntu-latest


  build-switch:
    needs: [ version ]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        driver: [opengl, deko3d]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Build OpenGL
        if: matrix.driver == 'opengl'
        run: |
          docker run --rm -v $(pwd):/data devkitpro/devkita64:20231108 bash -c "/data/scripts/build_switch.sh"

      - name: Upload dist OpenGL
        uses: actions/upload-artifact@v3
        if: matrix.driver == 'opengl'
        with:
          name: ${{ needs.version.outputs.DIST_NRO }}
          path: "cmake-build-switch/UpcomingSwitchGames.nro"

      - name: Build Deko3d
        if: matrix.driver == 'deko3d'
        run: |
          docker run --rm -v $(pwd):/data devkitpro/devkita64:20231108 bash -c "/data/scripts/build_switch_deko3d.sh"

      - name: Upload dist Deko3d
        uses: actions/upload-artifact@v3
        if: matrix.driver == 'deko3d'
        with:
          name: ${{ needs.version.outputs.DIST_NRO }}_deko3d
          path: "cmake-build-switch/UpcomingSwitchGames.nro"
